language: "python"

python: "3.6"

branches:
  only:
    - "master"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip
  - pip install flake8

script:
  - flake8 --max-complexity 10 --ignore=E501,W504
