language: "python"

python: "3.6"

branches:
  only:
    - "master"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install --upgrade pip
  - pip install -r test_requirements.txt

script:
  - make lint
  - cd src && coverage run -m py.test tests/*.py && coverage report
