trigger:
- "development"

pr:
- "development"

pool:
  vmImage: "Ubuntu-16.04"

steps:
- script: |
    make lint
    make check_release_file
  displayName: "Linting"

- task: "DownloadSecureFile@1"
  inputs:
    secureFile: "id_rsa_docstore"

- task: "DownloadSecureFile@1"
  inputs:
    secureFile: "docker_password.txt"

- script: |
    mkdir -p ~/.ssh
    cp $DOWNLOADSECUREFILE1_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    cp $DOWNLOADSECUREFILE2_SECUREFILEPATH docker_password.txt

    make autorelease

  condition: "eq(variables['Build.SourceBranch'], 'refs/heads/development')"
  displayName: "Create new release and publish a Docker image"
