version: "3"

services:
  elasticsearch:
    ports:
      - "9200:9200"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1"

  nginx:
    image: "nginx:alpine"
    ports:
      - "8062:80"
    volumes:
      - "/Users/alexwlchan/Documents/docstore:/usr/share/nginx/html"
