version: "3"

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1"

  nginx:
    image: "nginx:alpine"
    ports:
      - "8062:80"
    volumes:
      - "~/Documents/docstore:/usr/share/nginx/html"

  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    ports:
      - "8072:5042"
    volumes:
      - ".:/app"
