version: "2"

services:

  books:
    image: "docstore"
    ports:
      - "8062:8062"
    environment:
      - "PORT=8062"
    entrypoint:
      - python3
      - api.py
      - /documents
      - --title=books
    volumes:
      - ~/Documents/docstore/books:/documents

  correspondence:
    image: "docstore"
    ports:
      - "8072:8072"
    environment:
      - "PORT=8072"
    entrypoint:
      - python3
      - api.py
      - /documents
      - --title=correspondence
    volumes:
      - ~/Documents/docstore/correspondence:/documents

  manuals:
    image: "docstore"
    ports:
      - "8082:8082"
    environment:
      - "PORT=8082"
    entrypoint:
      - python3
      - api.py
      - /documents
      - --title=manuals
    volumes:
      - ~/Documents/docstore/manuals:/documents

